# Generated by Django 4.2.28 on 2026-02-24 13:06

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('SOLICITANTE', 'Solicitante'), ('APROVADOR', 'Aprovador'), ('ADMINISTRADOR', 'Administrador')], default='SOLICITANTE', max_length=20, verbose_name='Tipo de Usuário')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('conta_corrente', models.CharField(blank=True, max_length=20, verbose_name='Conta Corrente')),
                ('agencia', models.CharField(blank=True, max_length=10, verbose_name='Agência')),
                ('banco', models.CharField(blank=True, max_length=10, verbose_name='Código do Banco')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trecho_original', models.CharField(max_length=500, verbose_name='Trecho Original')),
                ('trecho_alterado', models.CharField(blank=True, help_text='Preencher apenas se houver alteração de rota', max_length=500, verbose_name='Trecho Alterado')),
                ('destino', models.CharField(max_length=200, verbose_name='Destino')),
                ('motivo', models.TextField(verbose_name='Motivo/Finalidade da Viagem')),
                ('classificacao_motivo', models.CharField(choices=[('SERVICO', 'A serviço da Cooperativa'), ('TREINAMENTO', 'Treinamento/Curso'), ('OUTRO', 'Outro')], max_length=20, verbose_name='Classificação do Motivo')),
                ('outro_motivo_descricao', models.TextField(blank=True, help_text='Obrigatório se classificação for "Outro"', verbose_name='Descrição do Outro Motivo')),
                ('data_autorizacao', models.DateField(verbose_name='Data da Autorização')),
                ('data_saida', models.DateField(verbose_name='Data da Saída')),
                ('data_chegada', models.DateField(verbose_name='Data da Chegada')),
                ('adiantamento', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Adiantamento (R$)')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Pendente de Aprovação'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('FINALIZADA', 'Finalizada')], default='RASCUNHO', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('aprovador', models.ForeignKey(limit_choices_to={'user_type': 'APROVADOR'}, on_delete=django.db.models.deletion.PROTECT, related_name='viagens_para_aprovar', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travels.costcenter', verbose_name='Centro de Custo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viagens_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Requisição de Viagem',
                'verbose_name_plural': 'Requisições de Viagem',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Veículo')),
                ('consumo_km_litro', models.DecimalField(decimal_places=2, help_text='Quantos quilômetros o veículo faz por litro', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Consumo (Km/L)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Veículo',
                'verbose_name_plural': 'Tipos de Veículo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='VehicleTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('km_rodado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='KM Rodado')),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor do Litro (R$)')),
                ('custo_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Calculado (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tipo_veiculo', models.ForeignKey(limit_choices_to={'ativo': True}, on_delete=django.db.models.deletion.PROTECT, to='travels.vehicletype', verbose_name='Tipo de Veículo')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens_veiculo', to='travels.travelrequest', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Viagem com Veículo Próprio',
                'verbose_name_plural': 'Viagens com Veículo Próprio',
            },
        ),
        migrations.CreateModel(
            name='VehicleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora_saida', models.TimeField(verbose_name='Hora de Saída')),
                ('hora_chegada', models.TimeField(verbose_name='Hora de Chegada')),
                ('hodometro_saida', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Hodômetro Saída (km)')),
                ('hodometro_chegada', models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Hodômetro Chegada (km)')),
                ('km_rodado', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='KM Rodado')),
                ('roteiro', models.CharField(max_length=500, verbose_name='Roteiro/Percurso')),
                ('objetivo', models.TextField(verbose_name='Motivo/Objetivo')),
                ('condutor', models.CharField(max_length=200, verbose_name='Condutor')),
                ('visto', models.CharField(blank=True, max_length=200, verbose_name='Visto')),
                ('viagem_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='travels.vehicletrip', verbose_name='Viagem Veículo')),
            ],
            options={
                'verbose_name': 'Log de Uso de Veículo',
                'verbose_name_plural': 'Logs de Uso de Veículo',
                'ordering': ['data', 'hora_saida'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('DIARIAS', 'Diárias e Extras de Hotel'), ('HOSPEDAGEM', 'Hospedagem'), ('REFEICOES', 'Refeições/Lanches'), ('CAFE_MANHA', 'Café da Manhã'), ('ALMOCO', 'Almoço'), ('JANTAR', 'Jantar'), ('PASSAGENS_AEREAS', 'Passagens Aéreas'), ('PASSAGENS_RODOVIARIAS', 'Passagens Rodoviárias'), ('PASSAGENS', 'Passagens (Outras)'), ('TAXI', 'Táxi'), ('UBER_APP', 'Uber/App de Transporte'), ('ONIBUS', 'Ônibus'), ('METRO_TREM', 'Metrô/Trem'), ('ESTACIONAMENTO', 'Estacionamento'), ('PEDAGIO', 'Pedágio'), ('COMBUSTIVEL', 'Combustível'), ('TELEFONEMAS', 'Telefonemas'), ('INTERNET', 'Internet/Dados Móveis'), ('CORREIO', 'Correio/Sedex'), ('MATERIAL_ESCRITORIO', 'Material de Escritório'), ('INSCRICAO_EVENTO', 'Inscrição em Evento/Curso'), ('DOCUMENTACAO', 'Documentação/Taxas'), ('LAVANDERIA', 'Lavanderia'), ('GORJETAS', 'Gorjetas'), ('OUTRAS', 'Outras Despesas')], max_length=32, verbose_name='Categoria')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor (R$)')),
                ('data_despesa', models.DateField(verbose_name='Data da Despesa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='travels.travelrequest', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['data_despesa'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPROVANTE_DESPESA', 'Comprovante de Despesa'), ('DOCUMENTO_VIAGEM', 'Documento da Viagem'), ('OUTRO', 'Outro')], default='COMPROVANTE_DESPESA', max_length=30, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='comprovantes/%Y/%m/%d/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('enviado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='travels.expense', verbose_name='Despesa')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='travels.travelrequest', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Anexo/Comprovante',
                'verbose_name_plural': 'Anexos/Comprovantes',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], max_length=20, verbose_name='Status')),
                ('parecer', models.TextField(verbose_name='Parecer')),
                ('data_aprovacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da Aprovação')),
                ('autoriza_debito_credito', models.BooleanField(default=False, verbose_name='Autoriza o débito/crédito conforme demonstrado')),
                ('aprovador', models.ForeignKey(limit_choices_to={'user_type__in': ['APROVADOR', 'ADMINISTRADOR']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
                ('viagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aprovacao', to='travels.travelrequest', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Aprovação',
                'verbose_name_plural': 'Aprovações',
            },
        ),
    ]
