# Generated by Django 5.2.11 on 2026-02-25 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo/departamento do usuário. Aprovadores só podem aprovar viagens de usuários do mesmo grupo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='travels.grupo', verbose_name='Grupo'),
        ),
    ]
